####################################################
# ESLint enforces the desired code style.
#
# Certain RULES WE WANT TO ENFORCE are commented
# out because refactoring is necessary.
####################################################

rules:
  array-bracket-spacing:
    - 1
    - never
    - singleValue: true
  # block-scoped-var: 2
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: true
  # camelcase: 2
  comma-dangle:
    - 2
    - never
  comma-spacing: 2
  comma-style:
    - 2
    - last
  # complexity:
  #   - 2
  #   - 11
  computed-property-spacing: 2
  consistent-return: 0
  # consistent-this:
  #   - 2
  #   - that
  curly:
    - 2
    - all
  default-case: 2
  dot-notation:
    - 2
    # - allowKeywords: false
  eol-last: 2
  eqeqeq: 2
  func-names: 0
  func-style:
    - 0
    - declaration
  guard-for-in: 2
  # handle-callback-err: 2
  indent:
    - 2
    - 2
    - SwitchCase: 1
  key-spacing:
    - 2
    - beforeColon: false
      afterColon: true
  keyword-spacing: 2
  linebreak-style:
    - 2
    - unix
  # max-nested-callbacks:
  #   - 2
  #   - 2
  new-cap: 2
  new-parens: 2
  # newline-after-var: 2
  no-array-constructor: 2
  no-caller: 2
  no-catch-shadow: 2
  no-cond-assign: 2
  no-constant-condition: 2
  no-continue: 2
  no-control-regex: 2
  no-debugger: 2
  no-delete-var: 2
  no-div-regex: 2
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  # no-else-return: 2
  # no-extra-parens: 2
  no-empty-character-class: 2
  no-empty:
    - 2
    - allowEmptyCatch: true
  no-eq-null: 2
  no-eval: 2
  no-ex-assign: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-boolean-cast: 2
  no-extra-semi: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-func-assign: 2
  no-implied-eval: 2
  no-inner-declarations:
    - 2
    - functions
  no-inline-comments: 2
  no-invalid-regexp: 2
  no-irregular-whitespace: 2
  no-iterator: 2
  no-label-var: 2
  no-labels: 2
  no-lone-blocks: 2
  no-lonely-if: 2
  no-loop-func: 2
  no-mixed-requires:
    - 2
    - false
  no-mixed-spaces-and-tabs: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-multiple-empty-lines: 2
  no-native-reassign: 2
  no-negated-in-lhs: 2
  no-nested-ternary: 2
  no-new-func: 2
  no-new-require: 2
  no-new-wrappers: 2
  no-new-object: 2
  no-new: 2
  no-obj-calls: 2
  no-octal-escape: 2
  no-octal: 2
  # no-param-reassign: 2
  # no-path-concat: 2
  no-process-env: 0
  # no-process-exit: 2
  no-proto: 2
  # no-redeclare: 2
  no-regex-spaces: 2
  no-restricted-modules: 2
  no-script-url: 2
  no-self-compare: 2
  # no-sequences: 2
  # no-shadow: 2
  no-shadow-restricted-names: 2
  no-spaced-func: 2
  no-sparse-arrays: 2
  # no-sync: 2
  no-ternary: 0
  no-throw-literal: 2
  no-trailing-spaces: 2
  no-undef-init: 2
  no-undefined: 0
  no-underscore-dangle: 2
  # no-unneeded-ternary: 2
  no-unreachable: 2
  no-unused-expressions: 2
  # no-unused-vars:
  #   - 2
  #   - vars: all
  #     args: after-used
  # no-use-before-define: 2
  no-void: 2
  no-warning-comments:
    - 1
    - terms:
        - todo
        - fixme
        - xxx
      location: start
  no-with: 2
  object-curly-spacing: 2
  one-var:
    - 2
    - never
  # operator-assignment:
  #   - 2
  #   - always
  operator-linebreak:
    - 2
    - after
  padded-blocks: 0
  # quote-props:
  #   - 2
  #   - as-needed
  quotes:
    - 2
    - single
  radix: 2
  semi-spacing:
    - 2
    - before: false
      after: true
  semi:
    - 2
    - always
  sort-vars: 2
  space-before-blocks:
    - 2
    - always
  space-before-function-paren:
    - 2
    - never
  space-in-parens:
    - 2
    - never
  space-infix-ops: 2
  space-unary-ops:
    - 2
    - words: false
      nonwords: false
  spaced-comment:
    - 2
    - always
  use-isnan: 2
  valid-jsdoc:
    - 2
    - prefer:
        return: return
  valid-typeof: 2
  # vars-on-top: 2
  wrap-iife: 2
  wrap-regex: 2
  yoda:
    - 2
    - never
