version: 0.1

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::234923831700:role/service-role/codebuild-suitec-service-role
  ComputeType: BUILD_GENERAL1_MEDIUM
  Image: aws/codebuild/nodejs:6.3.1
  Timeout: 60

phases:
  install:
    commands:
      - chmod 755 ./scripts/generate-build-stats.sh && ./scripts/generate-build-stats.sh
  pre_build:
    commands:
      - echo "pre_build phase"
  build:
    commands:
      - echo "build phase"
  post_build:
    commands:
      - echo "post_build phase"

artifacts:
  files:
    - '.bowerrc'
    - '.ebextensions/*'
    - '.elasticbeanstalk/*'
    - '.gitignore'
    - '**/*'
